//
//  Storyboard.swift
//  Prism
//
//  Created by Shai Mishali on 3/27/19.
//  Copyright © 2019 Gett. All rights reserved.
//

import Foundation

public struct AndroidStyleguideFileProvider: StyleguideFileProviding {
    public init() {
    }

    private let header = "    <!-- START: Generated by Prism Design System | https://github.com/gtforge/prism -->"
    private let footer = "    <!-- END: Generated by Prism Design System | https://github.com/gtforge/prism -->"

    public func colorsFileContents(for colors: [Prism.Project.Color]) -> String {
        let colorOutput = colors
            .map { color in 
                "    <color name=\"\(color.identity.android)\">\(color.argbValue)</color>"
            }
            .joined(separator: "\n")

        return """
        \(header)
        \(colorOutput)
        \(footer)
        """
    }

    public func textStylesFileContents(for project: Prism.Project) -> String {
        let textOutput = project.textStyles
            .map { textStyle in 
                let textColor: String
                
                if let matchedColor = project.colors.first(where: { $0.argbValue == textStyle.color.argbValue }) {
                    textColor = "@color/\(matchedColor.identity.android)"
                } else {
                    textColor = textStyle.color.argbValue
                }

                let normalizedFont = textStyle.fontFace.lowercased().replacingOccurrences(of: "-", with: "_")

                return """
                    <style name=\"\(textStyle.identity.android)\">
                        <item name="android:textSize">\(Int(textStyle.fontSize))sp</item>
                        <item name="android:fontFamily">@font/\(normalizedFont)</item>
                        <item name="android:textColor">\(textColor)</item>
                    </style>
                """

            }.joined(separator: "\n")

        return """
        \(header)
        \(textOutput)
        \(footer)
        """
    }
}
